### ISSUE TITLE
How to install this tool?

### ISSUE THREAD

**Issue by DanielSank** [google/addlicense#48]
I installed Go and then installed as instructed by the readme:
```
go get -u github.com/google/addlicense
```
`addlicense` is still not an executable on my system as far as I can tell. How do I run `addlicense`?

**Comment by xiumingzhang** [comment]
It is indeed not clear where the binary gets installed to. After some digging, I found it at `$HOME/go/bin/addlicense`.

**Comment by yannjor** [comment]
> How do I run addlicense?

As Xiuming mentioned, the binary gets installed to `$HOME/go/bin/addlicense`. If you want to be able to execute it anywhere on your system, I recommend setting a GOPATH environment variable. 

https://stackoverflow.com/questions/21001387/how-do-i-set-the-gopath-environment-variable-on-ubuntu-what-file-must-i-edit

**Comment by rodydavis** [comment]
> It is indeed not clear where the binary gets installed to. After some digging, I found it at `$HOME/go/bin/addlicense`.

That was it for me on MacOS! Thank you

**Comment by willnorris** [comment]
closing this, since it sounds like you got thing sorted out.  I'll also note that we [are working on publishing releases](https://github.com/google/addlicense/pull/83) with pre-built binaries for common platforms, so that will be another option soon.
