### ISSUE TITLE
Bug: Files generated by stringer are skipped

### ISSUE THREAD

**Issue by karlkfi** [google/addlicense#95]
I've found that in recent versions of addlicense, any file generated by stringer is skipped or has its license comment striped, if present.

The files generated by strinnger have the following file header comments:

```
// Code generated by "stringer -type=EVENT"; DO NOT EDIT.
```

The "EVENT" value changes between files but the rest of the comment is standard. I suspect something in that comment is causing the file to be skipped by addlicense.

Unfortunately, it doesn't just skip those files, it actively strips the addlicense comment if you add it manually.

**Comment by karlkfi** [comment]
Stringer, for reference: https://pkg.go.dev/golang.org/x/tools/cmd/stringer

**Comment by karlkfi** [comment]
Looks like this might be intentional:
- https://github.com/google/addlicense/blob/v1.0.0/main.go#L276
- https://github.com/google/addlicense/blob/v1.0.0/main.go#L254

**Comment by willnorris** [comment]
Skipping over generated files is certainly intentional.  I'm not sure how it would actively strip an existing addlicense comment, but if it is, then that's certainly a bug I'd like to be able to reproduce.

**Comment by karlkfi** [comment]
I suspect the stripping might have been from my makefile re-generating the files on top of files that previously had the header. So that's not actually addlicense behavior, sorry.

I'll close, since the behavior is intentional.
