### ISSUE TITLE
provide fail-on-diff flag to enable checking licence headers

### ISSUE THREAD

**Issue by developer-guy** [google/addlicense#99]
We (w/@dentrax) thought that in scenarios such as checking license headers, we use addlicence tool like the following way:

```shell
  license-check:
    name: license boilerplate check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.x'
      - name: Install addlicense
        run: go install github.com/google/addlicense@latest
      - name: Check license headers
        run: |
          set -e
          addlicense -l apache -c 'The Sigstore Authors' -v *
          git diff --exit-code
```

As you can see from the above GitHub Action definition, we use additional git commands to check that is there any leaked license headers in the codebase, so, what we are proposing is that we add this logic into addlicence tool with an additional flag-like `--fail-on-diff`.

**Comment by developer-guy** [comment]
would you mind assigning to us if you agree with this idea 🙋🏻‍♂️

**Comment by developer-guy** [comment]
kindly ping @willnorris

**Comment by willnorris** [comment]
Could you do this with the existing `-check` flag, which should return a non-zero status code if headers are missing ?

**Comment by developer-guy** [comment]
> 

ah thank you, we missed that flag 🤦🏻‍♂️

**Comment by willnorris** [comment]
It sounds like `-check` will work for you, so I'm going to go ahead and close this.  Feel free to reopen if it turns out that doesn't work.
